### PR TITLE
Fix all the broken things

### PR DESCRIPTION
**Pull request by sieren**
MQTT-Exec is currently broken due to API Changes in mqtt-client.
This PR restores functionality.

### CODE REVIEW

**Comment by jaywax** [comment]
Thanks Sieren, works like a charm on Freebsd12 ;)

**Comment by sieren** [comment]
Yayyy, too bad this repo seems dead.
I'll wait some more weeks and might just go ahead and do a complete rewrite and fork if nothing gets merged.

**Comment by denschu** [comment]
Sorry Guys for the late feedback... I'll merge the request now.

**Comment by jaywax** [comment]
Thanks Denshcu, will test it on Openbsd :)

**Pull request merged**
